version: '3'
networks:
    batman:
      driver: bridge

services:
  web:
    image: '8290911319/demovalley2'
    build: .
    ports:
      -  "80:1729" 
    networks:
      - batman

  database:
    image: 'mongo'
    ports:
      -  "27018:27017"
    networks:
      - batman
